# Generated by Django 4.1.3 on 2022-12-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='father_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Отчество'),
        ),
    ]
