# Generated by Django 4.1.3 on 2022-12-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_father_name_tutor_father_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='father_name',
        ),
        migrations.AddField(
            model_name='account',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество'),
        ),
    ]
